# tomcat
server:
  port: 4444
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    # 最大线程数
    max-threads: 1000
    max-http-header-size: 8096
    # 设置tomcat的basedir
    basedir: ${user.home}/tomcat/tmp
    # 最大连接数
    max-connections: 2000

# spring
spring:
  application:
    name: resume
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  # 数据库访问配置
  datasource:
    name: study
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/study?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    # 德鲁伊连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true

# 定义mapper.xml配置文件位置
mybatis:
  mapper-locations: mapper/*Mapper.xml
